#!/usr/bin/sh

clear

cd /home/lucas/projetos/sd-013-b-project-react-testing-library
if [ -z $1 ];
then
    npx stryker run
else
    for QUERY in $(ls stryker | grep -ie $1)
    do
        npx stryker run stryker/$QUERY
    done
fi
